// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.44
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace XSharpPowerTools
{
    internal sealed partial class Vsix
    {
        public const string Id = "XSharpPowerTools{1BDABBCB-67EC-4260-981D-E88D773490E3";
        public const string Name = "XSharpPowerTools.2022";
        public const string Description = @"A set of Visual Studio 2022 Tools for XSharp Developers";
        public const string Language = "en-US";
        public const string Version = "2.12";
        public const string Author = "Infominds Ag";
        public const string Tags = "";
        public const bool IsPreview = false;
    }
}
