// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace XSharpPowerTools
{
    internal sealed partial class Vsix
    {
        public const string Id = "XSharpPowerTools.821a9ef3-feda-412d-b004-767f380c7336";
        public const string Name = "XSharpPowerTools.2019";
        public const string Description = @"A set of Visual Studio 2019 tools for XSharp Developers";
        public const string Language = "en-US";
        public const string Version = "1.10.4";
        public const string Author = "Infominds Ag";
        public const string Tags = "";
    }
}
